[package]
name = "quasar"
version = "0.1.0"
authors = ["Anthony Nowell <anowell@gmail.com>"]
description = "An experimental rust-to-{wasm,asmjs} frontend framework."
repository = "https://github.com/anowell/quasar"

[dependencies]
rustc-serialize = "0.3.18"
downcast-rs = "0.1.2"
uuid = { version = "0.4.0", features = ["v4"] }

[dependencies.webplatform]
git = "https://github.com/anowell/rust-webplatform.git"
#path = "../rust-webplatform"
